FROM airhacks/glassfish
ENV ARCHIVE_NAME Captain.war
COPY target/${ARCHIVE_NAME} ${DEPLOYMENT_DIR}

ENV ZOOKEEPER_ADDRESS zook:2181
ENV ZOOKEEPER_CONNECTION_RETRY_MS 1000
ENV DISCOVERY_SERVICE_NAME Captain
EXPOSE 8080